.TH CHESS-VISION-TRAINER "1" "May 2019" "chess-vision-trainer 1.0.0" "User Commands"
.SH NAME
Chess Vision Trainer - Train your chess visualization skills.
.SH SYNOPSIS
.B chess-vision-trainer
.SH DESCRIPTION
Train your chess vision skills.
.RE
.SH BUGS
Report bugs to: <haroldfreeman@protonmail.com>
.br
Package home page: <https://github.com/haroldfreeman/chess-vision-trainer>
.SH COPYRIGHT
Copyright \(co 2019 Harold Freeman
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
